userview/sachu/sachu/Models/DanhMuc.cs
namespace sachu.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("DanhMuc")]
    public partial class DanhMuc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DanhMuc()
        {
            Saches = new HashSet<Sach>();
        }

        [Key]
        public int MaDM { get; set; }

        [StringLength(50)]
        public string TenDM { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sach> Saches { get; set; }
    }
}

userview/sachu/sachu/Controllers/AccessController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using sachu.Models;

namespace sachu.Controllers
{
    public class AccessController : Controller
    {
        private SachDB db = new SachDB();
        // GET: Access
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
       
        public ActionResult Register()
        {
            return View();
        }

        // POST: Admin/KhachHangs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register([Bind(Include = "MaKH,HoTen,DiaChi,Email,SoDT,MatKhau")] KhachHang khachHang)
        {
            if (ModelState.IsValid)
            {
                db.KhachHangs.Add(khachHang);
                db.SaveChanges();
                return RedirectToAction("Login");
            }

            return View(khachHang);
        }
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(string email, string matkhau)
        {
            if (ModelState.IsValid)
            {
                KhachHang user = db.KhachHangs.SingleOrDefault(m => m.Email.Equals(email) &&
                m.MatKhau.Equals(matkhau));
                if (user != null)
                {
                    Session["Hoten"] = user.HoTen;
                    Session["Emial"] = user.Email;
                    Session["IdUser"] = user.MaKH;
                    Session["taikhoan"] = user;
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ViewBag.error = "Sai tên đăng nhập hoặc mật khẩu";
                }
                 
            }

            return View();
        }
        public ActionResult Logout()
        {
            Session.Clear();
            return RedirectToAction("Index","Home");
        }

    }
}

userview/sachu/sachu/Controllers/GioHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using sachu.Models;

namespace sachu.Controllers
{
    public class GioHangController : Controller
    {
        private SachDB db = new SachDB();
        // GET: GioHang
      public List<GioHang> LayGioHang()
        {
            List<GioHang> dsmua = Session["giohang"] as List<GioHang>;
            if(dsmua == null)
            {
                dsmua = new List<GioHang>();
                Session["giohang"] = dsmua;
            }
            return dsmua;
        }
        public ActionResult ThemVaoGioHang( int masach,string url)
        {
            Sach sach = db.Saches.SingleOrDefault(n => n.MaSach == masach);
            if(sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            // lay session gio hang
            List<GioHang> dsmua = LayGioHang();
            //kiểm tra đã thêm sản phẩm này vào giỏ hàng lần nào chưa
            GioHang gh = dsmua.Find(n => n.GMaSach == masach);

            if (gh == null)
            {
                gh = new GioHang(masach);
                dsmua.Add(gh);
            }
           
            else
            {
                gh.GSoLuong++;
            }
            Session["giohang"] = dsmua;
            return Redirect(url);
        }
        //cập nhật giỏ hàng
        public ActionResult CapNhatGH(int masach)
        {
            //kiểm tra xem có sản phẩm này hay ko 
            Sach sach = db.Saches.SingleOrDefault(n => n.MaSach == masach);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            //nêu ko thực hiện cái này
            List <GioHang> dsmua = LayGioHang();
            GioHang sanpham = dsmua.SingleOrDefault(n => n.GMaSach == masach);
            if(sanpham != null)
            {
                sanpham.GSoLuong++;
            }
            return RedirectToAction("XemGioHang");

        }
        public ActionResult XoaSanPham(int masach)
        {
            //kiểm tra xem có sản phẩm này hay ko 
            Sach sach = db.Saches.SingleOrDefault(n => n.MaSach == masach);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            //nêu ko thực hiện cái này
            List<GioHang> dsmua = LayGioHang();
            GioHang sanpham = dsmua.SingleOrDefault(n => n.GMaSach == masach);
            if (sanpham != null)
            {
                dsmua.Remove(sanpham);
            }
            Session["giohang"] = dsmua;
            return RedirectToAction("XemGioHang");
        }
        public ActionResult XemGioHang()
        {
            //kiểm tra người dùng đăng nhập chưa nếu chưa bắt đăng nhập
            if (Session["Hoten"] == null)
            {
                return RedirectToAction("Login", "Access");
            }
            
            List<GioHang> dsmua = LayGioHang();
            return View(dsmua);
        }
        public int TongSoLuong()
        {
            int tongsoluong = 0;
            List<GioHang> dsmua = Session["giohang"] as List<GioHang>;
            if(dsmua != null)
            {
                tongsoluong = dsmua.Sum(n => n.GSoLuong);
            }
            return tongsoluong;
        }
        public double TongTien()
        {
            double tongtien = 0;
            List<GioHang> dsmua = Session["giohang"] as List<GioHang>;
            if (dsmua != null)
            {
                tongtien = dsmua.Sum(n => n.ThanhTien);
            }
            return tongtien;
        }
        public ActionResult DatHang()
        {
            DonHang dh = new DonHang();
            List<GioHang> gh = LayGioHang();
            KhachHang kh = (KhachHang)Session["taikhoan"];
            dh.MaKH = kh.MaKH;
            dh.NgayDat = DateTime.Now;
            //thêm đon hàng vào db
            db.DonHangs.Add(dh);
            db.SaveChanges();
            //thêm chi tiêt don hang
            foreach(var item in gh)
            {
                ChiTietDonHang ctdh = new ChiTietDonHang();
                ctdh.MaDH = dh.MaDH;
                ctdh.MaSach = item.GMaSach;
                ctdh.SoLuong = item.GSoLuong;
                ctdh.DonGia = decimal.Parse(item.GDonGia.ToString());
                db.ChiTietDonHangs.Add(ctdh);
            }
            db.SaveChanges();
            
            return RedirectToAction("Index","Home");

        }
    }
}

userview/sachu/sachu/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using sachu.Models;

namespace sachu.Controllers
{
    public class HomeController : Controller
    {
        private SachDB db = new SachDB();
        public ActionResult Index()
        {
            var sp = db.Saches.Select(m=>m);
         
            return View(sp);
        }

        public ActionResult ProductDetail(int ma)
        {
            var sach = db.Saches.Where(m => m.MaSach == ma);
            return View(sach);
        }
        public PartialViewResult FooterPartial()
        {
            return PartialView();
        }
        public PartialViewResult NavPartial()
        {
            return PartialView();
        }
        public PartialViewResult DanhMuc()
        {
            var danhmuc = db.DanhMucs.Select(m => m);
            return PartialView(danhmuc);
        }
        public ActionResult XemSPTDM(int madm)
        {
            var sach = db.Saches.Where(m => m.MaDM == madm).ToList();
            return View(sach);
        }
    }
}

userview/sachu/sachu/Views/Home/DanhMuc.cshtml
@model IEnumerable<sachu.Models.DanhMuc>

@foreach (var item in Model)
{
    <a href="@Url.Action("XemSPTDM","Home",new {madm= item.MaDM })" class="nav-item nav-link">@item.TenDM</a>
}

userview/sachu/sachu/Views/Home/FooterPartial.cshtml
<div class="container-fluid bg-secondary text-dark mt-5 pt-5">
    <div class="row px-xl-5 pt-5">
        <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
            <a href="" class="text-decoration-none">
                <h1 class="mb-4 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border border-white px-3 mr-1">E</span>Shopper</h1>
            </a>
            <p>Dolore erat dolor sit lorem vero amet. Sed sit lorem magna, ipsum no sit erat lorem et magna ipsum dolore amet erat.</p>
            <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>123 Street, New York, USA</p>
            <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
            <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
        </div>
        <div class="col-lg-8 col-md-12">
            <div class="row">
                <div class="col-md-4 mb-5">
                    <h5 class="font-weight-bold text-dark mb-4">Quick Links</h5>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-dark mb-2" href="index.html"><i class="fa fa-angle-right mr-2"></i>Home</a>
                        <a class="text-dark mb-2" href="shop.html"><i class="fa fa-angle-right mr-2"></i>Our Shop</a>
                        <a class="text-dark mb-2" href="detail.html"><i class="fa fa-angle-right mr-2"></i>Shop Detail</a>
                        <a class="text-dark mb-2" href="cart.html"><i class="fa fa-angle-right mr-2"></i>Shopping Cart</a>
                        <a class="text-dark mb-2" href="checkout.html"><i class="fa fa-angle-right mr-2"></i>Checkout</a>
                        <a class="text-dark" href="contact.html"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <h5 class="font-weight-bold text-dark mb-4">Quick Links</h5>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-dark mb-2" href="index.html"><i class="fa fa-angle-right mr-2"></i>Home</a>
                        <a class="text-dark mb-2" href="shop.html"><i class="fa fa-angle-right mr-2"></i>Our Shop</a>
                        <a class="text-dark mb-2" href="detail.html"><i class="fa fa-angle-right mr-2"></i>Shop Detail</a>
                        <a class="text-dark mb-2" href="cart.html"><i class="fa fa-angle-right mr-2"></i>Shopping Cart</a>
                        <a class="text-dark mb-2" href="checkout.html"><i class="fa fa-angle-right mr-2"></i>Checkout</a>
                        <a class="text-dark" href="contact.html"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <h5 class="font-weight-bold text-dark mb-4">Newsletter</h5>
                    <form action="">
                        <div class="form-group">
                            <input type="text" class="form-control border-0 py-4" placeholder="Your Name" required="required" />
                        </div>
                        <div class="form-group">
                            <input type="email" class="form-control border-0 py-4" placeholder="Your Email"
                                   required="required" />
                        </div>
                        <div>
                            <button class="btn btn-primary btn-block border-0 py-3" type="submit">Subscribe Now</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>
<!-- Footer End -->
<!-- Back to Top -->
<a href="#" class="btn btn-primary back-to-top"><i class="fa fa-angle-double-up"></i></a>

userview/sachu/sachu/Views/Home/Index.cshtml
@model IEnumerable<sachu.Models.Sach>
@{
    ViewBag.Title = "Home Page";
}


    <div class="container-fluid pt-5">
        <div class="text-center mb-4">
            <h2 class="section-title px-5"><span class="px-2">Products List</span></h2>
        </div>
        <div class="row px-xl-5 pb-3">
            @foreach (var item in Model)
            {
                <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
                    <div class="card product-item border-0 mb-4">
                        <div class="card-header product-img position-relative overflow-hidden bg-transparent border p-0">
                            <img class="img-fluid w-100" src="~/assets/img/@item.AnhBia" alt="">
                        </div>
                        <div class="card-body border-left border-right text-center p-0 pt-4 pb-3">
                            <h6 class="text-truncate mb-3">@item.TenSach</h6>
                            <div class="d-flex justify-content-center">
                                <h6>@item.GiaBan</h6><h6 class="text-muted ml-2">VNĐ</h6>
                            </div>
                        </div>
                        <div class="card-footer d-flex justify-content-between bg-light border">
                            <a href="@Url.Action("ProductDetail","Home",new {ma= item.MaSach })" class="btn btn-sm text-dark p-0"><i class="fas fa-eye text-primary mr-1"></i>View Detail</a>
                            <a href="@Url.Action("ThemVaoGioHang","GioHang",new {masach = @item.MaSach,url= Request.Url.ToString()})" class="btn btn-sm text-dark p-0"><i class="fas fa-shopping-cart text-primary mr-1"></i>Add To Cart</a>
                        </div>
                    </div>
                </div>
            }
            


        </div>
    </div>

userview/sachu/sachu/Views/Home/NavPartial.cshtml
<div class="container-fluid">

    <div class="row align-items-center py-3 px-xl-5">
        <div class="col-lg-3 d-none d-lg-block">
            <a href="" class="text-decoration-none">
                <h1 class="m-0 display-5 font-weight-semi-bold">
                <span class="text-primary font-weight-bold border px-3 mr-1">Book</span>Shop</h1>
            </a>
        </div>
        <div class="col-lg-6 col-6 text-left">
            <form action="">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for products">
                    <div class="input-group-append">
                        <span class="input-group-text bg-transparent text-primary">
                            <i class="fa fa-search"></i>
                        </span>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-lg-3 col-6 text-right">
            <a href="~/GioHang/XemGiohang" class="btn border">
                <i class="fas fa-heart text-primary"></i>
                <span class="badge">0</span>
            </a>
            <a href="~/GioHang/XemGioHang" class="btn border">
                <i class="fas fa-shopping-cart text-primary"></i>
                <span class="badge">0</span>
            </a>
        </div>
    </div>
</div>
<!-- Topbar End -->
<!-- Navbar Start -->
<div class="container-fluid mb-5">
    <div class="row border-top px-xl-5">
        <div class="col-lg-3 d-none d-lg-block">
            <a class="btn shadow-none d-flex align-items-center justify-content-between bg-primary text-white w-100" data-toggle="collapse" href="#navbar-vertical" style="height: 65px; margin-top: -1px; padding: 0 30px;">
                <h6 class="m-0">Danh mục sách</h6>
                <i class="fa fa-angle-down text-dark"></i>
            </a>
            <nav class="collapse show navbar navbar-vertical navbar-light align-items-start p-0 border border-top-0 border-bottom-0" id="navbar-vertical">
                <div class="navbar-nav w-100 overflow-hidden" style="height: 410px">
                  
                    @Html.Action("DanhMuc","Home")  
                    <a href="" class="nav-item nav-link">Jeans</a>

                </div>
            </nav>
        </div>
        <div class="col-lg-9">
            <nav class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0">
                <a href="" class="text-decoration-none d-block d-lg-none">
                    <h1 class="m-0 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border px-3 mr-1">E</span>Shopper</h1>
                </a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <div class="navbar-nav mr-auto py-0">
                        <a href="~/Home/Index" class="nav-item nav-link active">Home</a>
                        <a href="shop.html" class="nav-item nav-link">Shop</a>
                        <a href="detail.html" class="nav-item nav-link">Shop Detail</a>
                        <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Pages</a>
                            <div class="dropdown-menu rounded-0 m-0">
                                <a href="cart.html" class="dropdown-item">Shopping Cart</a>
                                <a href="checkout.html" class="dropdown-item">Checkout</a>
                            </div>
                        </div>
                        <a href="contact.html" class="nav-item nav-link">Contact</a>
                    </div>
                    <div class="navbar-nav ml-auto py-0">
                       @* @{ Html.RenderAction("Menu", "Shop");}*@

                        @if (Session["Hoten"] != null)
                        {
                            
                                <a href="" class="active">
                                    Xin chào ,@Session["Hoten"]-@Session["Email"]
                                </a>
                                <span>-</span>
                                <a href="@Url.Action("Logout","Access")" class="active">
                                    <span class="glyphicon glyphicon-log-out"></span>
                                    Đăng xuất
                                </a>
                           

                        }

                        else
                        {
                            
                                <a href="@Url.Action("Register","Access")" class="active">
                                    <span class="glyphicon glyphicon-user"></span>
                                    Đăng ký
                                </a>
                                <span>-</span>
                           
                                <a href="@Url.Action("Login","Access")" class="active">
                                    <span class="glyphicon glyphicon-log-in"></span>
                                    Đăng nhập
                                </a>
                            
                        }
                    </div>
                </div>
            </nav>
            <div id="header-carousel" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active" style="height: 410px;">
                        <img class="img-fluid" src="~/assets/img/carousel-1.jpg" alt="Image">
                        <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                            <div class="p-3" style="max-width: 700px;">
                                <h4 class="text-light text-uppercase font-weight-medium mb-3">10% Off Your First Order</h4>
                                <h3 class="display-4 text-white font-weight-semi-bold mb-4">Fashionable Dress</h3>
                                <a href="" class="btn btn-light py-2 px-3">Shop Now</a>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item" style="height: 410px;">
                        <img class="img-fluid" src="~/assets/img/carousel-2.jpg" alt="Image">
                        <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                            <div class="p-3" style="max-width: 700px;">
                                <h4 class="text-light text-uppercase font-weight-medium mb-3">10% Off Your First Order</h4>
                                <h3 class="display-4 text-white font-weight-semi-bold mb-4">Reasonable Price</h3>
                                <a href="" class="btn btn-light py-2 px-3">Shop Now</a>
                            </div>
                        </div>
                    </div>
                </div>
                <a class="carousel-control-prev" href="#header-carousel" data-slide="prev">
                    <div class="btn btn-dark" style="width: 45px; height: 45px;">
                        <span class="carousel-control-prev-icon mb-n2"></span>
                    </div>
                </a>
                <a class="carousel-control-next" href="#header-carousel" data-slide="next">
                    <div class="btn btn-dark" style="width: 45px; height: 45px;">
                        <span class="carousel-control-next-icon mb-n2"></span>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>

userview/sachu/sachu/Views/Home/XemSPTDM.cshtml
@model IEnumerable<sachu.Models.Sach>

@{
    ViewBag.Title = "XemSPTDM";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Danh sách sản phẩm theo danh mục</h2>

<div class="container-fluid pt-5">
    <div class="text-center mb-4">
        <h2 class="section-title px-5"><span class="px-2">Products List</span></h2>
    </div>
    <div class="row px-xl-5 pb-3">
        @foreach (var item in Model)
        {
            <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
                <div class="card product-item border-0 mb-4">
                    <div class="card-header product-img position-relative overflow-hidden bg-transparent border p-0">
                        <img class="img-fluid w-100" src="~/assets/img/@item.AnhBia" alt="">
                    </div>
                    <div class="card-body border-left border-right text-center p-0 pt-4 pb-3">
                        <h6 class="text-truncate mb-3">@item.TenSach</h6>
                        <div class="d-flex justify-content-center">
                            <h6>@item.GiaBan</h6><h6 class="text-muted ml-2">VNĐ</h6>
                        </div>
                    </div>
                    <div class="card-footer d-flex justify-content-between bg-light border">
                        <a href="@Url.Action("ProductDetail","Home",new {ma= item.MaSach })" class="btn btn-sm text-dark p-0"><i class="fas fa-eye text-primary mr-1"></i>View Detail</a>
                        <a href="" class="btn btn-sm text-dark p-0"><i class="fas fa-shopping-cart text-primary mr-1"></i>Add To Cart</a>
                    </div>
                </div>
            </div>
        }



    </div>
</div>